version: '3'
services:
  web:
    build: ./services/users
    ports:
    - 5000:5000
    volumes:
    - ./services/feed:/usr/src/app
    links:
    - redis

  redis:
    image: redis

  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    ports:
      - 27017:27017
