version: '3'

services:
  backend:
    build: ./services/backend
    ports:
      - 5000
    volumes:
      - ./services/backend:/usr/src/app
    depends_on:
      - mongo

  crawler:
    build: ./services/crawler
    volumes:
      - ./services/crawler:/usr/src/app
    depends_on:
      - mongo
      - backend

  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo:/data/db
    ports:
      - 27017
    command: mongod --smallfiles --logpath=/dev/null 
